// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeterinariaApi.Data;

#nullable disable

namespace VeterinariaApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250716070903_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan@example.com",
                            Nombre = "Juan Pérez",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ElMartinez@example.com",
                            Nombre = "Eliana Martinez",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "p@example",
                            Nombre = "Paula",
                            Telefono = "213123123213"
                        });
                });

            modelBuilder.Entity("VeterinariaApi.Models.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("HistoriaClinica");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnostico = "Esterilización",
                            Fecha = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Reposo",
                            PacienteId = 1,
                            Tratamiento = "Antibiótico por 7 días"
                        },
                        new
                        {
                            Id = 2,
                            Diagnostico = "Gastroenteritis Leve",
                            Fecha = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Ninguno",
                            PacienteId = 2,
                            Tratamiento = "Ninguno"
                        });
                });

            modelBuilder.Entity("VeterinariaApi.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Edad = 4,
                            Especie = "perra",
                            Nombre = "luna",
                            Peso = 0f,
                            Raza = "caniche"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Edad = 3,
                            Especie = "perro",
                            Nombre = "roco",
                            Peso = 0f,
                            Raza = "labrador"
                        });
                });

            modelBuilder.Entity("VeterinariaApi.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Atendido",
                            FechaHora = new DateTime(2025, 7, 14, 0, 31, 0, 0, DateTimeKind.Utc),
                            Notas = "Paciente revisado, en buen estado",
                            PacienteId = 1,
                            VeterinarioId = 3
                        });
                });

            modelBuilder.Entity("VeterinariaApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "agustina@example.com",
                            Nombre = "Natalia",
                            PasswordHash = "$2a$11$USTCLvu0SeTHIcUeoTzoVeE0wcxjRZc4JH8WSD8UUS7kUYvFW7RDy",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sandra@example.com",
                            Nombre = "Sandra López",
                            PasswordHash = "$2a$11$USTCLvu0SeTHIcUeoTzoVeE0wcxjRZc4JH8WSD8UUS7kUYvFW7RDy",
                            Rol = "Recepcionista"
                        },
                        new
                        {
                            Id = 3,
                            Email = "marceloG@gmail.com",
                            Nombre = "Marcelo ",
                            PasswordHash = "$2a$11$B8J3fEqgACv/Uvo9vBNv2uFr6XhORqFgAxpwRTulC2P2W9ybPHsAy",
                            Rol = "Veterinario"
                        });
                });

            modelBuilder.Entity("VeterinariaApi.Models.HistoriaClinica", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Paciente", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Cliente", "Cliente")
                        .WithMany("Mascotas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Turno", b =>
                {
                    b.HasOne("VeterinariaApi.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApi.Models.Usuario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VeterinariaApi.Models.Cliente", b =>
                {
                    b.Navigation("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
